# Re-usable workflow for project analysis with qodana
name: Qodana

on:
  workflow_call:
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.1.9
        env:
          QODANA_LINTER: ${{ env.QODANA_TOKEN == '' && 'jetbrains/qodana-jvm-community:2024.2' || 'jetbrains/qodana-jvm:2024.2' }}
        with:
          use-caches: false
          upload-result: true
          args: --baseline,.qodana/qodana.sarif.json,--linter,${{ env.QODANA_LINTER }},--commit,f3d3c8e4d9f8dece6eadf40d3a7b95b80a5336e3

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
